# This file stores configurations for your Shopify app.

scopes = "read_orders,read_products,read_product_listings,write_orders,read_fulfillments,write_fulfillments,write_merchant_managed_fulfillment_orders,read_merchant_managed_fulfillment_orders"
